// <auto-generated />
namespace FindMyAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAddDisplayName_AddUniqueConstrains : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAddDisplayName_AddUniqueConstrains));
        
        string IMigrationMetadata.Id
        {
            get { return "201711210439228_UserAddDisplayName_AddUniqueConstrains"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
