// <auto-generated />
namespace FindMyAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncreaseURLLinkSizeTo150 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncreaseURLLinkSizeTo150));
        
        string IMigrationMetadata.Id
        {
            get { return "201711211843087_IncreaseURLLinkSizeTo150"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
